"""initial tables

Revision ID: c52503255538
Revises: 
Create Date: 2026-09-22 11:23:03.684805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c52503255538'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('sent_at', sa.String(length=25), nullable=False),
    sa.Column('mode', sa.String(length=5), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('delivered', sa.Integer(), nullable=False),
    sa.Column('deferred', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command',
    sa.Column('received_at', sa.String(length=25), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('allowed', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=20), nullable=False),
    sa.Column('args_json', sa.Text(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.create_index('ix_command_received', ['received_at'], unique=False)

    op.create_table('index_level',
    sa.Column('index_name', sa.String(length=10), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_name', 'date', name='uq_index')
    )
    op.create_table('instrument',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('listed_on', sa.String(length=10), nullable=True),
    sa.Column('delisted_on', sa.String(length=10), nullable=True),
    sa.Column('prev_code', sa.String(length=6), nullable=True),
    sa.Column('shares_outstanding', sa.Integer(), nullable=True),
    sa.Column('shares_asof', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('monthly_report',
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('mode', sa.String(length=5), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('factor_effects_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_month', 'mode', name='uq_report')
    )
    op.create_table('trading_calendar',
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('is_trading_day', sa.Integer(), nullable=False),
    sa.Column('open_at', sa.String(length=5), nullable=True),
    sa.Column('close_at', sa.String(length=5), nullable=True),
    sa.Column('is_month_end', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('valuation',
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('mode', sa.String(length=5), nullable=False),
    sa.Column('cash', sa.Integer(), nullable=False),
    sa.Column('stock_value', sa.Integer(), nullable=False),
    sa.Column('index_value', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('external_flow', sa.Integer(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.Column('pnl_vs_principal', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('daily_bar',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('series_no', sa.Integer(), nullable=False),
    sa.Column('open', sa.Integer(), nullable=False),
    sa.Column('high', sa.Integer(), nullable=False),
    sa.Column('low', sa.Integer(), nullable=False),
    sa.Column('close', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('traded', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.String(length=25), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'series_no', 'trade_date', name='uq_bar')
    )
    with op.batch_alter_table('daily_bar', schema=None) as batch_op:
        batch_op.create_index('ix_bar_date', ['trade_date'], unique=False)

    op.create_table('filing',
    sa.Column('rcept_no', sa.String(length=14), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('report_kind', sa.String(length=12), nullable=False),
    sa.Column('rcept_date', sa.String(length=10), nullable=False),
    sa.Column('corrects_rcept_no', sa.String(length=14), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('collected_at', sa.String(length=25), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rcept_no')
    )
    with op.batch_alter_table('filing', schema=None) as batch_op:
        batch_op.create_index('ix_filing_inst_rcept', ['instrument_id', 'rcept_date'], unique=False)

    op.create_table('gate_record',
    sa.Column('checked_at', sa.String(length=25), nullable=False),
    sa.Column('paper_days', sa.Integer(), nullable=False),
    sa.Column('rebalances', sa.Integer(), nullable=False),
    sa.Column('order_errors', sa.Integer(), nullable=False),
    sa.Column('selection_match', sa.Float(), nullable=False),
    sa.Column('return_gap', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(length=4), nullable=False),
    sa.Column('approved_by_command_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.String(length=25), nullable=True),
    sa.Column('capital', sa.Integer(), nullable=True),
    sa.Column('first_month_ratio', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_command_id'], ['command.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument_status',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('starts_on', sa.String(length=10), nullable=False),
    sa.Column('ends_on', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instrument_status', schema=None) as batch_op:
        batch_op.create_index('ix_status_inst_range', ['instrument_id', 'starts_on', 'ends_on'], unique=False)

    op.create_table('position',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('avg_cost', sa.Integer(), nullable=False),
    sa.Column('first_bought_on', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.String(length=25), nullable=False),
    sa.Column('updated_by', sa.String(length=14), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id')
    )
    op.create_table('reconciliation',
    sa.Column('checked_at', sa.String(length=25), nullable=False),
    sa.Column('mode', sa.String(length=5), nullable=False),
    sa.Column('bot_cash', sa.Integer(), nullable=False),
    sa.Column('broker_cash', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('resolution', sa.String(length=8), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('resolved_by_command_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.String(length=25), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_command_id'], ['command.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_review',
    sa.Column('asof', sa.String(length=10), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=False),
    sa.Column('adopted_json', sa.Text(), nullable=False),
    sa.Column('diff_json', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(length=8), nullable=True),
    sa.Column('decided_by_command_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.String(length=25), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_command_id'], ['command.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_state',
    sa.Column('mode', sa.String(length=5), nullable=False),
    sa.Column('halted', sa.Integer(), nullable=False),
    sa.Column('buy_suspended', sa.Integer(), nullable=False),
    sa.Column('orders_blocked', sa.Integer(), nullable=False),
    sa.Column('peak_equity', sa.Integer(), nullable=False),
    sa.Column('peak_reset_at', sa.String(length=25), nullable=True),
    sa.Column('principal', sa.Integer(), nullable=False),
    sa.Column('live_since', sa.String(length=25), nullable=True),
    sa.Column('gate_record_id', sa.Integer(), nullable=True),
    sa.Column('first_month_cap', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat_at', sa.String(length=25), nullable=True),
    sa.Column('updated_at', sa.String(length=25), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['gate_record_id'], ['gate_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_snapshot',
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.String(length=10), nullable=False),
    sa.Column('period_kind', sa.String(length=8), nullable=False),
    sa.Column('consolidated', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Integer(), nullable=True),
    sa.Column('operating_income', sa.Integer(), nullable=True),
    sa.Column('net_income', sa.Integer(), nullable=True),
    sa.Column('net_income_owner', sa.Integer(), nullable=True),
    sa.Column('equity', sa.Integer(), nullable=True),
    sa.Column('equity_owner', sa.Integer(), nullable=True),
    sa.Column('eps', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'period_end', 'period_kind', 'consolidated', name='uq_snapshot')
    )
    with op.batch_alter_table('financial_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_inst_period', ['instrument_id', 'period_end'], unique=False)

    op.create_table('reconciliation_diff',
    sa.Column('reconciliation_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('bot_qty', sa.Integer(), nullable=False),
    sa.Column('broker_qty', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_config',
    sa.Column('factors_json', sa.Text(), nullable=False),
    sa.Column('min_price', sa.Integer(), nullable=False),
    sa.Column('min_amount20', sa.Integer(), nullable=False),
    sa.Column('min_mcap', sa.Integer(), nullable=False),
    sa.Column('n_holdings', sa.Integer(), nullable=False),
    sa.Column('trend_filter', sa.Integer(), nullable=False),
    sa.Column('index_weight', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.String(length=10), nullable=False),
    sa.Column('approved_by_command_id', sa.Integer(), nullable=True),
    sa.Column('source_review_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_command_id'], ['command.id'], ),
    sa.ForeignKeyConstraint(['source_review_id'], ['rule_review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision',
    sa.Column('asof', sa.String(length=10), nullable=False),
    sa.Column('mode', sa.String(length=5), nullable=False),
    sa.Column('strategy_config_id', sa.Integer(), nullable=False),
    sa.Column('code_version', sa.String(length=40), nullable=False),
    sa.Column('cash_switch', sa.Integer(), nullable=False),
    sa.Column('index_rebalance', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('budget_per_slot', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['strategy_config_id'], ['strategy_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.create_index('ix_decision_status', ['status'], unique=False)
        batch_op.create_index('uq_decision_real', ['asof', 'mode'], unique=True, sqlite_where=sa.text("status != 'replay'"))

    op.create_table('score',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('factors_json', sa.Text(), nullable=False),
    sa.Column('pct_json', sa.Text(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Integer(), nullable=False),
    sa.Column('skip_reason', sa.String(length=8), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', 'instrument_id', name='uq_score')
    )
    op.create_table('trade_order',
    sa.Column('idem_key', sa.String(length=30), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=6), nullable=False),
    sa.Column('limit_price', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('broker_order_no', sa.String(length=20), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('reject_reason', sa.String(length=40), nullable=True),
    sa.Column('sent_at', sa.String(length=25), nullable=True),
    sa.Column('closed_at', sa.String(length=25), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idem_key')
    )
    with op.batch_alter_table('trade_order', schema=None) as batch_op:
        batch_op.create_index('ix_order_decision', ['decision_id'], unique=False)
        batch_op.create_index('ix_order_status', ['status'], unique=False)

    op.create_table('fill',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('filled_at', sa.String(length=25), nullable=False),
    sa.Column('broker_fill_no', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['trade_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'broker_fill_no', name='uq_fill')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fill')
    with op.batch_alter_table('trade_order', schema=None) as batch_op:
        batch_op.drop_index('ix_order_status')
        batch_op.drop_index('ix_order_decision')

    op.drop_table('trade_order')
    op.drop_table('score')
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.drop_index('uq_decision_real', sqlite_where=sa.text("status != 'replay'"))
        batch_op.drop_index('ix_decision_status')

    op.drop_table('decision')
    op.drop_table('strategy_config')
    op.drop_table('reconciliation_diff')
    with op.batch_alter_table('financial_snapshot', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_inst_period')

    op.drop_table('financial_snapshot')
    op.drop_table('bot_state')
    op.drop_table('rule_review')
    op.drop_table('reconciliation')
    op.drop_table('position')
    with op.batch_alter_table('instrument_status', schema=None) as batch_op:
        batch_op.drop_index('ix_status_inst_range')

    op.drop_table('instrument_status')
    op.drop_table('gate_record')
    with op.batch_alter_table('filing', schema=None) as batch_op:
        batch_op.drop_index('ix_filing_inst_rcept')

    op.drop_table('filing')
    with op.batch_alter_table('daily_bar', schema=None) as batch_op:
        batch_op.drop_index('ix_bar_date')

    op.drop_table('daily_bar')
    op.drop_table('valuation')
    op.drop_table('trading_calendar')
    op.drop_table('monthly_report')
    op.drop_table('instrument')
    op.drop_table('index_level')
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.drop_index('ix_command_received')

    op.drop_table('command')
    op.drop_table('alert')
    # ### end Alembic commands ###
